### ISSUE TITLE
"Status: Online" Implementation - How do we know when users are online? 

### ISSUE THREAD

**Issue by JakeIwen** [carlpeaslee/bouncetribe#12]
I don't see any obvious clues/methods in the schema or Auth0 besides log in/out history. 

Here is schema if there are clues
https://api.graph.cool/simple/v1/bt-api

**Comment by carlpeaslee** [comment]
Yeah, I think the easiest thing to do here might be to create a new column on the user model called 'isOnline' that holds a boolean and then create two mutations inside maybe the root template container that are like:

(this is pseudocode)

```javascript

componentDidMount(){
 --set this users 'isOnline' to true
}

componentDidUnmount(){
 --set this users 'isOnline' to false
}

```

**Comment by carlpeaslee** [comment]
in the future we might be better off doing some stuff with sessions but this feels like it would work for now

**Comment by JakeIwen** [comment]
Ok @RPowerHimself  - gonna need graphcool access for this one.

**Comment by RPowerHimself** [comment]
@carlpeaslee is it okay for me to go into the GraphCool schema and add that new column to the user model? I see where it should go. I just want to make sure I won't mess up any DB syncs or migrations by adding it.

**Comment by carlpeaslee** [comment]
Yeah, if you know where to put it you can just do it.

**Comment by JakeIwen** [comment]
I can't get this to reflect when tabs are closed. Dunno if componentWillUnmount() even fires then or what
This runs like we want it to when it is applied to pages where the user navigates away from them (like applied to Dashboard, navigating to Tribe) 

But with SetUserOffline event is not reflected in our database when the tab is closed, so using it in template in this manner doesn't have any effect and isOnline remains true;

Any ideas @carlpeaslee ?

```
constructor(props) {
      super(props);
        this.state = { };
      this.handleClose = this.handleClose.bind(this);
    }

  componentDidMount() {
    document.addEventListener('onbeforeunload', this.handleClose());
    this.props.relay.commitUpdate(
      new SetUserOnline({
        user: this.props.viewer.user
      })
    )
  }

  componentWillUnmount() {
    document.removeEventListener('onbeforeunload', this.handleClose());
    this.userOffline();
  }

  handleClose() {
    this.props.relay.commitUpdate(
      new SetUserOffline({
        user: this.props.viewer.user
      })
    )
  }
```
Also, SetUserOffline() was tested by putting it within componentDidMount()  and is definitely working

**Comment by RPowerHimself** [comment]
Sweet, I added the column.

**Comment by JakeIwen** [comment]
@carlpeaslee 
so handleClose will be run BEFORE the page actually closes. 
Is there some type of async issue... something involving nested promises... (sorry... maybe wrong terminology)... that would result in the page being closed BEFORE the actual POST to graphQL is made? 

```
handleClose() {
    this.props.relay.commitUpdate(
      new SetUserOffline({
        user: this.props.viewer.user
      })
    )
  }
```

**Comment by carlpeaslee** [comment]
Correct. I’d have to look and see what the contract for
‘componentWillUnmount” says but my understanding is that the code inside it
will always run even if you close the window. You should check it out
though.

You might also want to set up some vanilla javascript listeners on the
window looking for various close and navigation events if I’m wrong.

We are just using this information to track whether or not users are online
for like chatting and stuff, right?

**Comment by JakeIwen** [comment]
Yes - that little green dot on the user avatar.
I have not been able to get !isOnline to graphQL on page close.
Even if it runs all the code, its not waiting on a promise resolve, and I think that's the issue.

**Comment by carlpeaslee** [comment]
Hmm... Maybe we should rethink it and it should be something like this:

-user model has a 'lastPing" field
-on load, set up a timer that sends graphcool a ping every 15 seconds with a timestamp.
-store the timestamp in the 'lastPing' field. 
-if a user's lastPing field is more than thirty seconds old, they are offline

**Comment by JakeIwen** [comment]
done; with interval ping

**Comment by carlpeaslee** [comment]
Nicely done!
