### ISSUE TITLE
CSS: Tribe member Icons

### ISSUE THREAD

**Issue by JakeIwen** [carlpeaslee/bouncetribe#13]
They seem to arbitrarily appear elliptical. Page refresh yields different combinations of circular and oval icons.

![image](https://user-images.githubusercontent.com/20415982/31432732-e7f266ea-ae3c-11e7-8a9d-90ef87fac9b6.png)

**Comment by RPowerHimself** [comment]
Yeah I've noticed that as well. Seems to happen with some of the SVGs and genre labels. No idea why.

**Comment by JakeIwen** [comment]
Fixed (as well as table row spacing) with BtAvatar
