### ISSUE TITLE
Why Migrate Relay

### ISSUE THREAD

**Issue by JakeIwen** [carlpeaslee/bouncetribe#17]
Was asking a friend for advice on migrating to Relay modern and he asked "why are you migrating?".
Which sort of stumped me.
What are the otherwise unresolvable, or hard-to-resolve issues that Relay Modern will address?

It will certainly have its own snags as well: is it worth it to put in the time/$ to get this taken care of right now?

**Comment by carlpeaslee** [comment]
Tbh, I think it’s not worth it to migrate.

**Comment by JakeIwen** [comment]
okay - Will plan not to migrate before beta release/more funding
