### ISSUE TITLE
Audio Player - Loop Tracks

### ISSUE THREAD

**Issue by josephbarsness** [carlpeaslee/bouncetribe#18]
**When you reach the end of a song, have the audio player loop and start the song again.**

So far what I have figured out I think you need to import the icon like this -

_import Loop from 'material-ui/svg-icons/av/loop'_

and then I feel like the location where this should be is bouncetribe/src/components/AudioPlayer.js and when I look through I find a play, pause and toggle code block and I mean I feel like all I would need to do is to have the loop button when clicked it would allow the song to continue to play but when it reaches the end that it would just start from the beginning.  I'm sure there's a simple way to code that but honestly I just don't have the experience to understand what that would be.

Any assistance would be greatly appreciated.  Thank you!!!

Joey

**Comment by carlpeaslee** [comment]
So i think there might actually be a really easy solution here where you just add the prop "loop" to the html audio element... But I don't know if there might be other problems...

This might be helpful: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Audio_streamsWeb_Audio_API

**Comment by josephbarsness** [comment]
Okay Carl...let me look that up and see if I can figure it out.  If not I will let you know.
