### ISSUE TITLE
Very Interesting Component Initializing

### ISSUE THREAD

**Issue by JakeIwen** [carlpeaslee/bouncetribe#27]
Does any of the following make sense:
calling `constructor(props)` and `super(props)` without using `props` or `this.props`, respectively
calling `setState` in the constructor
having a constructor AND a `state={...}` outside of that constructor

*Would it make the most sense to move everything below except propTypes into the constructor ?*

![image](https://user-images.githubusercontent.com/20415982/33116945-4af72176-cf2c-11e7-88bc-5edc13d39841.png)
![image](https://user-images.githubusercontent.com/20415982/33117325-a08ebb70-cf2d-11e7-88cd-23cc4fbe1638.png)

@carlpeaslee

**Comment by JakeIwen** [comment]
Ok I see that setState was called as a promise resolve. 
I feel like theres a better way to implement the getAllGenres than inside the constructor though.

**Comment by JakeIwen** [comment]
ehh i will just make some assumptions

**Comment by carlpeaslee** [comment]
Sorry, I was out of town. Let me know if you have more questions about this.
