### ISSUE TITLE
Create New Dashboard

### ISSUE THREAD

**Issue by carlpeaslee** [carlpeaslee/bouncetribe#6]
My suggestions for how to approach this task:

1. Look at the new dashboard design and break up each of its features into discreet, independent components .
2. Divy up each of these components amongst devs who want to work on this. 
3. The easy way to make each of these components would be to just make them accept data as props and pass back any actions as call backs to their parents. The "right way" / "hard way" would be to make them each data independent Relay containers that can fetch their own data and make their own mutations. I'd suggest doing things the easy way for now. 
4. Once you have each of these subcomponents created, you can make a relay-connected data container for them. This is the one for the current feed: https://github.com/BounceTribe/bouncetribe/blob/master/src/containers/Feed.js
5. In order to have your new dashboard appear instead of the feed page, you'll have to change the reference to "Feed" in the routing file: https://github.com/BounceTribe/bouncetribe/blob/master/src/routing/index.js.

Does that help? Let me know if you have more questions.

**Comment by JakeIwen** [comment]
Mornin' Carl -

Couple git questions for ya:

What is our git flow for development here?
Push completed and functional features to test0?
When do we push to master?

I sent my two pull requests (View All Notifications and Correct Login
Errors) straight to master. We can roll it back or merge to test...

Thanks,
Jake

**Comment by carlpeaslee** [comment]
I believe `test0` is currently set to automatically deploy to test.bouncetribe.com –– currently `master` doesn't deploy anywhere. 

I think the goal would be eventually have `master` automatically deploy to bouncetribe.com. Then we'd do a flow of something like: developer branch / issue branch -> `test0` -> `master`. Even better would be if we set up unit tests and then did continuous integration.
