### ISSUE TITLE
"Tribe Member" button - incorrect state

### ISSUE THREAD

**Issue by JakeIwen** [carlpeaslee/bouncetribe#9]
When viewing another tribe member's profile, the button option to add them to your tribe still exists on page load. 

![image](https://user-images.githubusercontent.com/20415982/31367294-e36186c6-ad3b-11e7-8e35-f4f6482ddb3b.png)

If you click the button, then it changes state to this, jsut as it would if it were actually adding them to your tribe. 

![image](https://user-images.githubusercontent.com/20415982/31367319-338542b4-ad3c-11e7-9273-44cf4903702b.png)

Maybe should just say "Remove Tribe Member" right away  instead?
Haven't looked into depth of issue.

**Comment by JakeIwen** [comment]
This button also has a third state, something like "Add to Tribe"

**Comment by RPowerHimself** [comment]
Yeah, it should really have 3 different states:

1. Not Friends (Click Add to Tribe)
2. Friend Request Sent (Request Pending)
3. Friends (Click to Remove from Tribe)

**Comment by JakeIwen** [comment]
Also it is a little strange that when user==User, the button is actually a LINK to your tribe page.

**Comment by JakeIwen** [comment]
what about  when there is a Tribe request from them? "Accept Invite"?
Could you put the words you want on the button in quotes so i know for sure?

**Comment by JakeIwen** [comment]
Maybe we should have something besides an implicit statement on a button inform the user that they are in fact in the same tribe. like a badge above the button or something

**Comment by JakeIwen** [comment]
fixed.
